cmake_minimum_required(VERSION 3.23)
project(rayplayer VERSION 1.0.0 LANGUAGES CXX C)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_BUILD_TYPE Release)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/cmake/dist)

# mpv
find_library(MPV_LIB mpv.dll HINTS "${PROJECT_SOURCE_DIR}/external/mpv")

# raylib
set(CUSTOMIZE_BUILD ON)
set(USE_AUDIO OFF)
set(SUPPORT_MODULE_RMODELS OFF)
set(SUPPORT_MODULE_RAUDIO OFF)
set(SUPPORT_CAMERA_SYSTEM OFF)
set(SUPPORT_GIF_RECORDING OFF)
set(SUPPORT_FILEFORMAT_GIF OFF)
set(SUPPORT_IMAGE_EXPORT OFF)
set(SUPPORT_IMAGE_GENERATION OFF)
set(SUPPORT_IMAGE_MANIPULATION OFF)
set(SUPPORT_FILEFORMAT_OBJ OFF)
set(SUPPORT_FILEFORMAT_MTL OFF)
set(SUPPORT_FILEFORMAT_IQM OFF)
set(SUPPORT_FILEFORMAT_GLTF OFF)
set(SUPPORT_FILEFORMAT_VOX OFF)
set(SUPPORT_FILEFORMAT_M3D OFF)
set(SUPPORT_MESH_GENERATION OFF)
set(SUPPORT_FILEFORMAT_WAV OFF)
set(SUPPORT_FILEFORMAT_OGG OFF)
set(SUPPORT_FILEFORMAT_MP3 OFF)
set(SUPPORT_FILEFORMAT_QOA OFF)
set(SUPPORT_FILEFORMAT_XM OFF)
set(SUPPORT_FILEFORMAT_MOD OFF)
set(SUPPORT_SAVE_PNG OFF)
set(SUPPORT_SCREEN_CAPTURE OFF)
# raylib 6.0 cmake bug workaround
set(SUPPORT_BUSY_WAIT_LOOP OFF)
set(SUPPORT_CUSTOM_FRAME_CONTROL OFF)
set(SUPPORT_FILEFORMAT_TGA OFF)
set(SUPPORT_FILEFORMAT_JPG OFF)
set(SUPPORT_FILEFORMAT_PSD OFF)
set(SUPPORT_FILEFORMAT_HDR OFF)
set(SUPPORT_FILEFORMAT_PIC OFF)
set(SUPPORT_FILEFORMAT_PNM OFF)
set(SUPPORT_FILEFORMAT_KTX OFF)
set(SUPPORT_FILEFORMAT_ASTC OFF)
set(SUPPORT_FILEFORMAT_PKM OFF)
set(SUPPORT_FILEFORMAT_PVR OFF)
set(SUPPORT_FILEFORMAT_BDF OFF)
set(SUPPORT_GPU_SKINNING OFF)
set(SUPPORT_FILEFORMAT_FLAC OFF)
add_subdirectory(external/raylib)

# rayplayer
set(RAYPLAYER_FILES
    ${PROJECT_SOURCE_DIR}/src/main.cpp
    ${PROJECT_SOURCE_DIR}/src/app.cpp

    ${PROJECT_SOURCE_DIR}/src/mediaplayer/mediaplayer.cpp

    ${PROJECT_SOURCE_DIR}/src/ui/mediaplayerpage.cpp
)

add_executable(${CMAKE_PROJECT_NAME} ${RAYPLAYER_FILES})

if(MINGW)
    target_link_options(${CMAKE_PROJECT_NAME} PRIVATE "-static" "-static-libgcc" "-static-libstdc++" "-Wl,-Bstatic" "-lwinpthread")    
endif()

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE stdc++exp raylib ${MPV_LIB})
target_include_directories(${CMAKE_PROJECT_NAME}
    PRIVATE 
    ${PROJECT_SOURCE_DIR}/src
    ${PROJECT_SOURCE_DIR}/external/mpv/include
    ${PROJECT_SOURCE_DIR}/external/raylib/src
    ${PROJECT_SOURCE_DIR}/external/raylib/src/external/glfw/include
)